server:
  port: 8823
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blogs_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: mysql
  jpa:
    generate-ddl: on
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug
